spring:
  #profiles:
    #active: test
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

# Open Api
springdoc:
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    operationsSorter: alpha
    path: /swagger
